namespace Entra21_trabalho_02.Chakra
{
    internal enum Natureza
    {
        Aço,
        Água,
        Calor,
        Chama,
        Cristal,
        Ebulição,
        Escuro,
        Espuma,
        Explosão,
        Fogo,
        Fusão,
        Gelo,
        Lama,
        Madeira,
        Magnetismo,
        Pó,
        Raio,
        Rápido,
        Tempestade,
        Terra,
        Tufão,
        Vento,
        Yang,
        Yin
    }
}